import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import {NextIntlClientProvider} from 'next-intl';
import { getMessages } from 'next-intl/server';
import { Toaster } from 'sonner';

import './globals.scss';


const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};


export default async function RootLayout({
  children,
  params: { locale }
}: Readonly<{
  children: React.ReactNode;
  params: { locale: string; }
}>) {
  // const locale = await getLocale();
  const messages = await getMessages();

  // const location = navigator.geolocation
  // console.log('GEOLOCATOIN', location)

  return (
    <html lang={locale}>
      <body className={inter.className}>
        <NextIntlClientProvider messages={messages}>
          <Toaster />
          {children}
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
